"""
Django settings for pfd_workbench_v02 project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return

    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_env_file(PROJECT_ROOT / "api.env")
_load_env_file(BASE_DIR / ".env")


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw.strip())
    except (TypeError, ValueError):
        return default


def _env_int_list(name: str, default: tuple[int, ...]) -> tuple[int, ...]:
    raw = os.getenv(name)
    if raw is None:
        return default
    values: list[int] = []
    for part in raw.split(","):
        stripped = part.strip()
        if not stripped:
            continue
        try:
            values.append(int(stripped))
        except ValueError:
            continue
    return tuple(values or default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-*ess+!!2buh7*)9uid2w8))mj^+2@d*j5nf^6z-hj-*uroa$#%",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"
TESTING = "test" in sys.argv

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,pfdtoolkit.org,www.pfdtoolkit.org",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "wb_workspaces",
    "wb_investigations",
    "wb_runs",
    "wb_sharing",
    "wb_auditlog",
    "wb_notifications",
    "wb_collections",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "pfd_workbench_v02.performance.PerformanceInstrumentationMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pfd_workbench_v02.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pfd_workbench_v02.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Production: set DATABASE_URL (e.g. Railway Postgres).
# Local fallback remains sqlite for developer convenience.
database_url = os.getenv("DATABASE_URL", "").strip()
if database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=600,
            ssl_require=False,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://pfdtoolkit.org,https://www.pfdtoolkit.org",
    ).split(",")
    if origin.strip()
]

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Auth0 configuration
AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN", "oreliandata.uk.auth0.com")
AUTH0_CLIENT_ID = os.getenv("AUTH0_CLIENT_ID", "uirpul9BDRViPlCtkKJqDK7KrCPKQilD")
AUTH0_CLIENT_SECRET = os.getenv("AUTH0_CLIENT_SECRET", "")
AUTH0_SCOPES = os.getenv("AUTH0_SCOPES", "openid profile email")
AUTH0_CALLBACK_PATH = "/auth/callback/"
AUTH0_CALLBACK_URL = os.getenv(
    "AUTH0_CALLBACK_URL",
    f"http://127.0.0.1:8000{AUTH0_CALLBACK_PATH}",
)
AUTH0_POST_LOGOUT_REDIRECT_URI = os.getenv(
    "AUTH0_POST_LOGOUT_REDIRECT_URI",
    "http://127.0.0.1:8000/",
)
PFD_ADMIN_EMAIL = os.getenv("PFD_ADMIN_EMAIL", "sam.osian@oreliandata.co.uk").lower()
WORKBENCH_BASE_URL = os.getenv("WORKBENCH_BASE_URL", "http://127.0.0.1:8000").rstrip("/")

# Artifact storage configuration
# `file` keeps artifact paths on local disk.
# `object_storage` uploads artifact files to S3-compatible object storage.
ARTIFACT_STORAGE_BACKEND = os.getenv("ARTIFACT_STORAGE_BACKEND", "file").strip().lower()
ARTIFACT_OBJECT_STORAGE_BUCKET = os.getenv("ARTIFACT_OBJECT_STORAGE_BUCKET", "").strip()
ARTIFACT_OBJECT_STORAGE_REGION = os.getenv("ARTIFACT_OBJECT_STORAGE_REGION", "").strip()
ARTIFACT_OBJECT_STORAGE_ENDPOINT_URL = os.getenv("ARTIFACT_OBJECT_STORAGE_ENDPOINT_URL", "").strip()
ARTIFACT_OBJECT_STORAGE_ACCESS_KEY_ID = os.getenv("ARTIFACT_OBJECT_STORAGE_ACCESS_KEY_ID", "").strip()
ARTIFACT_OBJECT_STORAGE_SECRET_ACCESS_KEY = os.getenv(
    "ARTIFACT_OBJECT_STORAGE_SECRET_ACCESS_KEY",
    "",
).strip()
ARTIFACT_OBJECT_STORAGE_PREFIX = os.getenv("ARTIFACT_OBJECT_STORAGE_PREFIX", "workbench-artifacts").strip()
ARTIFACT_STORAGE_DELETE_LOCAL_AFTER_UPLOAD = _env_bool(
    "ARTIFACT_STORAGE_DELETE_LOCAL_AFTER_UPLOAD",
    True,
)
ARTIFACT_ENFORCE_OBJECT_STORAGE_IN_PRODUCTION = _env_bool(
    "ARTIFACT_ENFORCE_OBJECT_STORAGE_IN_PRODUCTION",
    True,
)
ARTIFACT_RETENTION_DAYS = _env_int("ARTIFACT_RETENTION_DAYS", 365)
ARTIFACT_SOFT_DELETE_DAYS = _env_int("ARTIFACT_SOFT_DELETE_DAYS", 30)
ARTIFACT_VERIFY_CHECKSUM = _env_bool("ARTIFACT_VERIFY_CHECKSUM", True)

# Lifecycle maintenance
# Sliding inactivity window for keepalive/expiry policies.
LIFECYCLE_INACTIVITY_DAYS = int(os.getenv("LIFECYCLE_INACTIVITY_DAYS", "365"))
LIFECYCLE_ARCHIVE_RETENTION_DAYS = int(os.getenv("LIFECYCLE_ARCHIVE_RETENTION_DAYS", "60"))
# Debounce interval to reduce write amplification from repeated view refreshes.
LIFECYCLE_VIEW_DEBOUNCE_SECONDS = int(os.getenv("LIFECYCLE_VIEW_DEBOUNCE_SECONDS", "0"))

# Notification/email delivery
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", False)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@pfdtoolkit.org")

# Run guardrails and reliability controls
RUN_GUARDRAILS_ENABLED = _env_bool("RUN_GUARDRAILS_ENABLED", True)
MAX_RUNS_PER_USER_PER_DAY = _env_int("MAX_RUNS_PER_USER_PER_DAY", 20)
MAX_RUNS_PER_WORKBOOK_PER_DAY = _env_int("MAX_RUNS_PER_WORKBOOK_PER_DAY", 40)
MAX_CONCURRENT_RUNS_PER_USER = _env_int("MAX_CONCURRENT_RUNS_PER_USER", 2)
MAX_CONCURRENT_RUNS_GLOBAL = _env_int("MAX_CONCURRENT_RUNS_GLOBAL", 12)
RUN_LAUNCH_RATE_LIMIT_USER_PER_MINUTE = _env_int("RUN_LAUNCH_RATE_LIMIT_USER_PER_MINUTE", 10)
RUN_LAUNCH_RATE_LIMIT_IP_PER_MINUTE = _env_int("RUN_LAUNCH_RATE_LIMIT_IP_PER_MINUTE", 30)

RUN_RETRY_ENABLED = _env_bool("RUN_RETRY_ENABLED", True)
RUN_RETRY_MAX_ATTEMPTS = _env_int("RUN_RETRY_MAX_ATTEMPTS", 3)
RUN_RETRY_BACKOFF_SECONDS = _env_int_list("RUN_RETRY_BACKOFF_SECONDS", (30, 120, 600))
RUN_RETRY_JITTER_PCT = _env_int("RUN_RETRY_JITTER_PCT", 20)
RUN_STAGE_TIMEOUT_SECONDS = _env_int("RUN_STAGE_TIMEOUT_SECONDS", 1800)
RUN_TOTAL_TIMEOUT_SECONDS = _env_int("RUN_TOTAL_TIMEOUT_SECONDS", 7200)
RUN_STUCK_THRESHOLD_SECONDS = _env_int("RUN_STUCK_THRESHOLD_SECONDS", 1800)
WORKER_HEARTBEAT_STALE_SECONDS = _env_int("WORKER_HEARTBEAT_STALE_SECONDS", 120)

# Performance instrumentation (MVP baseline)
# Logs warnings for slow requests/queries via standard Django logging handlers.
PERF_REQUEST_LOGGING_ENABLED = _env_bool("PERF_REQUEST_LOGGING_ENABLED", True)
PERF_SLOW_REQUEST_MS = int(os.getenv("PERF_SLOW_REQUEST_MS", "800"))
PERF_SLOW_QUERY_MS = int(os.getenv("PERF_SLOW_QUERY_MS", "200"))
PERF_ADD_RESPONSE_TIMING_HEADER = _env_bool("PERF_ADD_RESPONSE_TIMING_HEADER", False)

# Workspace credential encryption
# Optional: set a dedicated Fernet key (base64 urlsafe, 32-byte key material).
# If unset, the app derives a fallback key from SECRET_KEY.
CREDENTIAL_ENCRYPTION_KEY = os.getenv("CREDENTIAL_ENCRYPTION_KEY", "").strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
