# Generated by Django 5.2.12 on 2026-04-19 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wb_investigations", "0001_initial"),
        ("wb_workspaces", "0002_workspacecredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="investigation",
            constraint=models.UniqueConstraint(
                fields=("workspace",), name="uniq_investigation_per_workspace"
            ),
        ),
    ]
