from django.urls import path

from . import views


urlpatterns = [
    path(
        "workbooks/investigation/start/",
        views.investigation_start,
        name="workbook-investigation-start",
    ),
    path(
        "workspaces/investigation/start/",
        views.investigation_start,
        name="investigation-start",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigation/",
        views.investigation_entry,
        name="workbook-investigation-entry",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigations/",
        views.investigation_list,
        name="workbook-investigation-list",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigations/<uuid:investigation_id>/",
        views.investigation_detail,
        name="workbook-investigation-detail",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigations/<uuid:investigation_id>/update/",
        views.investigation_update,
        name="workbook-investigation-update",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigations/<uuid:investigation_id>/wizard/",
        views.investigation_wizard,
        name="workbook-investigation-wizard",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigations/<uuid:investigation_id>/export/queue/",
        views.queue_export_bundle,
        name="workbook-investigation-export-queue",
    ),
    path(
        "workbooks/<uuid:workbook_id>/investigations/<uuid:investigation_id>/share/public/",
        views.share_investigation_public_link,
        name="workbook-investigation-share-public",
    ),

    path(
        "workspaces/<uuid:workbook_id>/investigation/",
        views.investigation_entry,
        name="investigation-entry",
    ),
    path(
        "workspaces/<uuid:workbook_id>/investigations/",
        views.investigation_list,
        name="investigation-list",
    ),
    path(
        "workspaces/<uuid:workbook_id>/investigations/<uuid:investigation_id>/",
        views.investigation_detail,
        name="investigation-detail",
    ),
    path(
        "workspaces/<uuid:workbook_id>/investigations/<uuid:investigation_id>/update/",
        views.investigation_update,
        name="investigation-update",
    ),
    path(
        "workspaces/<uuid:workbook_id>/investigations/<uuid:investigation_id>/wizard/",
        views.investigation_wizard,
        name="investigation-wizard",
    ),
    path(
        "workspaces/<uuid:workbook_id>/investigations/<uuid:investigation_id>/export/queue/",
        views.queue_export_bundle,
        name="investigation-export-queue",
    ),
    path(
        "workspaces/<uuid:workbook_id>/investigations/<uuid:investigation_id>/share/public/",
        views.share_investigation_public_link,
        name="investigation-share-public",
    ),
]
