# Generated by Django 5.2.12 on 2026-04-18 21:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wb_investigations", "0001_initial"),
        ("wb_workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("filter", "Filter"),
                            ("themes", "Themes"),
                            ("extract", "Extract"),
                            ("export", "Export"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("cancelling", "Cancelling"),
                            ("cancelled", "Cancelled"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed out"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                ("worker_id", models.CharField(blank=True, max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("input_config_json", models.JSONField(default=dict)),
                ("query_start_date", models.DateField(blank=True, null=True)),
                ("query_end_date", models.DateField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancel_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancel_requested_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="wb_investigations.investigation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="wb_workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("filtered_dataset", "Filtered dataset"),
                            ("theme_summary", "Theme summary"),
                            ("theme_assignments", "Theme assignments"),
                            ("extraction_table", "Extraction table"),
                            ("bundle_export", "Bundle export"),
                            ("preview", "Preview"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("db", "DB"),
                            ("object_storage", "Object storage"),
                            ("file", "File"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "storage_uri",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("metadata_json", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="wb_runs.investigationrun",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="wb_workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("stage", "Stage"),
                            ("progress", "Progress"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("info", "Info"),
                            ("cancel_check", "Cancel check"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("payload_json", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="wb_runs.investigationrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="investigationrun",
            index=models.Index(
                fields=["workspace", "status", "queued_at"], name="idx_run_ws_stat_qd"
            ),
        ),
        migrations.AddIndex(
            model_name="investigationrun",
            index=models.Index(
                fields=["investigation", "-created_at"], name="idx_run_inv_cr_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="investigationrun",
            index=models.Index(
                fields=["status", "updated_at"], name="idx_run_status_updated"
            ),
        ),
        migrations.AddConstraint(
            model_name="investigationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("progress_percent__isnull", True),
                    models.Q(
                        ("progress_percent__gte", 0), ("progress_percent__lte", 100)
                    ),
                    _connector="OR",
                ),
                name="chk_run_progress_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="investigationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("query_start_date__isnull", True),
                    ("query_end_date__isnull", True),
                    ("query_end_date__gte", models.F("query_start_date")),
                    _connector="OR",
                ),
                name="chk_run_query_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="runartifact",
            index=models.Index(
                fields=["workspace", "status", "expires_at"], name="idx_art_ws_stat_exp"
            ),
        ),
        migrations.AddIndex(
            model_name="runartifact",
            index=models.Index(
                fields=["run", "artifact_type"], name="idx_artifact_run_type"
            ),
        ),
        migrations.AddIndex(
            model_name="runartifact",
            index=models.Index(
                fields=["last_viewed_at"], name="idx_artifact_last_viewed"
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("size_bytes__isnull", True),
                    ("size_bytes__gte", 0),
                    _connector="OR",
                ),
                name="chk_artifact_size_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(
                fields=["run", "created_at"], name="idx_run_event_run_created"
            ),
        ),
    ]
