# Generated by Django 5.2.12 on 2026-05-06 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_investigations', '0002_investigation_uniq_investigation_per_workspace'),
        ('wb_runs', '0003_runworkerheartbeat'),
        ('wb_workspaces', '0008_user_llm_config_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationrun',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_investigation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_investigation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='investigationrun',
            index=models.Index(fields=['status', 'requires_approval', 'approval_status', 'queued_at'], name='idx_run_stat_appr_qd'),
        ),
    ]
