from django.urls import path

from . import views


urlpatterns = [
    path(
        "workbooks/llm-config/save/",
        views.save_active_llm_config,
        name="workbook-llm-config-save",
    ),
    path(
        "workbooks/llm-config/credentials/clear/",
        views.clear_active_llm_credential,
        name="workbook-llm-config-credential-clear",
    ),
    path("workbooks/", views.dashboard, name="workbook-dashboard"),
    path(
        "workbooks/<uuid:workbook_id>/activate/",
        views.activate_workspace,
        name="workbook-activate",
    ),
    path(
        "workbooks/<uuid:workbook_id>/open/",
        views.open_workspace,
        name="workbook-open",
    ),
    path(
        "workbooks/<uuid:workbook_id>/reports/panel/",
        views.workspace_reports_panel,
        name="workbook-reports-panel",
    ),
    path(
        "workbooks/<uuid:workbook_id>/reports/export.csv",
        views.workspace_export_csv,
        name="workbook-export-csv",
    ),
    path(
        "workbooks/<uuid:workbook_id>/archive/",
        views.archive_workspace_view,
        name="workbook-archive",
    ),
    path(
        "workbooks/<uuid:workbook_id>/restore/",
        views.restore_workspace_view,
        name="workbook-restore",
    ),
    path(
        "workbooks/<uuid:workbook_id>/delete/",
        views.delete_workspace_view,
        name="workbook-delete",
    ),
    path("workbooks/public/", views.public_workspace_list, name="workbook-public-list"),
    path("workbooks/<uuid:workbook_id>/", views.workspace_detail, name="workbook-detail"),
    path(
        "workbooks/<uuid:workbook_id>/members/add/",
        views.add_member,
        name="workbook-member-add",
    ),
    path(
        "workbooks/<uuid:workbook_id>/members/<uuid:membership_id>/update/",
        views.update_member,
        name="workbook-member-update",
    ),
    path(
        "workbooks/<uuid:workbook_id>/members/<uuid:membership_id>/remove/",
        views.remove_member,
        name="workbook-member-remove",
    ),
    path(
        "workbooks/<uuid:workbook_id>/credentials/save/",
        views.save_credential,
        name="workbook-credential-save",
    ),
    path(
        "workbooks/<uuid:workbook_id>/credentials/remove/",
        views.remove_credential,
        name="workbook-credential-remove",
    ),
    path(
        "workbooks/<uuid:workbook_id>/excluded-reports/add/",
        views.exclude_report,
        name="workbook-excluded-report-add",
    ),
    path(
        "workbooks/<uuid:workbook_id>/excluded-reports/<uuid:exclusion_id>/restore/",
        views.restore_excluded_report,
        name="workbook-excluded-report-restore",
    ),
    path(
        "workbooks/<uuid:workbook_id>/state/undo/",
        views.undo_workspace_state_view,
        name="workbook-state-undo",
    ),
    path(
        "workbooks/<uuid:workbook_id>/state/redo/",
        views.redo_workspace_state_view,
        name="workbook-state-redo",
    ),
    path(
        "workbooks/<uuid:workbook_id>/state/start-over/",
        views.start_over_workspace_state_view,
        name="workbook-state-start-over",
    ),
    path(
        "workbooks/<uuid:workbook_id>/state/revert-reports/",
        views.revert_workspace_reports_view,
        name="workbook-state-revert-reports",
    ),

    path("workspaces/", views.dashboard, name="workspace-dashboard"),
    path(
        "workspaces/<uuid:workbook_id>/activate/",
        views.activate_workspace,
        name="workspace-activate",
    ),
    path(
        "workspaces/<uuid:workbook_id>/open/",
        views.open_workspace,
        name="workspace-open",
    ),
    path(
        "workspaces/<uuid:workbook_id>/reports/panel/",
        views.workspace_reports_panel,
        name="workspace-reports-panel",
    ),
    path(
        "workspaces/<uuid:workbook_id>/reports/export.csv",
        views.workspace_export_csv,
        name="workspace-export-csv",
    ),
    path(
        "workspaces/<uuid:workbook_id>/archive/",
        views.archive_workspace_view,
        name="workspace-archive",
    ),
    path(
        "workspaces/<uuid:workbook_id>/restore/",
        views.restore_workspace_view,
        name="workspace-restore",
    ),
    path(
        "workspaces/<uuid:workbook_id>/delete/",
        views.delete_workspace_view,
        name="workspace-delete",
    ),
    path("workspaces/public/", views.public_workspace_list, name="workspace-public-list"),
    path("workspaces/<uuid:workbook_id>/", views.workspace_detail, name="workspace-detail"),
    path(
        "workspaces/<uuid:workbook_id>/members/add/",
        views.add_member,
        name="workspace-member-add",
    ),
    path(
        "workspaces/<uuid:workbook_id>/members/<uuid:membership_id>/update/",
        views.update_member,
        name="workspace-member-update",
    ),
    path(
        "workspaces/<uuid:workbook_id>/members/<uuid:membership_id>/remove/",
        views.remove_member,
        name="workspace-member-remove",
    ),
    path(
        "workspaces/<uuid:workbook_id>/credentials/save/",
        views.save_credential,
        name="workspace-credential-save",
    ),
    path(
        "workspaces/<uuid:workbook_id>/credentials/remove/",
        views.remove_credential,
        name="workspace-credential-remove",
    ),
    path(
        "workspaces/<uuid:workbook_id>/excluded-reports/add/",
        views.exclude_report,
        name="workspace-excluded-report-add",
    ),
    path(
        "workspaces/<uuid:workbook_id>/excluded-reports/<uuid:exclusion_id>/restore/",
        views.restore_excluded_report,
        name="workspace-excluded-report-restore",
    ),
    path(
        "workspaces/<uuid:workbook_id>/state/undo/",
        views.undo_workspace_state_view,
        name="workspace-state-undo",
    ),
    path(
        "workspaces/<uuid:workbook_id>/state/redo/",
        views.redo_workspace_state_view,
        name="workspace-state-redo",
    ),
    path(
        "workspaces/<uuid:workbook_id>/state/start-over/",
        views.start_over_workspace_state_view,
        name="workspace-state-start-over",
    ),
    path(
        "workspaces/<uuid:workbook_id>/state/revert-reports/",
        views.revert_workspace_reports_view,
        name="workspace-state-revert-reports",
    ),
    path(
        "workspaces/llm-config/save/",
        views.save_active_llm_config,
        name="workspace-llm-config-save",
    ),
    path(
        "workspaces/llm-config/credentials/clear/",
        views.clear_active_llm_credential,
        name="workspace-llm-config-credential-clear",
    ),
]
