# Generated by Django 5.2.12 on 2026-04-18 21:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("is_listed", models.BooleanField(default=False)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=12,
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[("edit", "Edit"), ("read_only", "Read-only")],
                        default="read_only",
                        max_length=16,
                    ),
                ),
                ("can_manage_members", models.BooleanField(default=False)),
                ("can_manage_shares", models.BooleanField(default=False)),
                ("can_run_workflows", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="wb_workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("state_json", models.JSONField(default=dict)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("edit", "Edit"),
                            ("undo", "Undo"),
                            ("redo", "Redo"),
                            ("restore", "Restore"),
                            ("system", "System"),
                        ],
                        default="edit",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_revisions",
                        to="wb_workspaces.workspacerevision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="wb_workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["visibility", "is_listed"], name="idx_ws_vis_listed"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["updated_at"], name="idx_ws_updated_at"),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                fields=("created_by", "slug"), name="uniq_workspace_created_by_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["workspace", "role"], name="idx_wsm_workspace_role"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(fields=["user"], name="idx_wsm_user"),
        ),
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"), name="uniq_workspace_membership_user"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacerevision",
            index=models.Index(
                fields=["workspace", "-revision_number"],
                name="idx_wsr_workspace_revdesc",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacerevision",
            index=models.Index(fields=["created_at"], name="idx_wsr_created_at"),
        ),
        migrations.AddConstraint(
            model_name="workspacerevision",
            constraint=models.UniqueConstraint(
                fields=("workspace", "revision_number"),
                name="uniq_workspace_revision_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_number__gt", 0)),
                name="chk_workspace_revision_number_gt_zero",
            ),
        ),
    ]
