# Generated by Django 5.2.12 on 2026-04-19 19:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wb_workspaces", "0002_workspacecredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceReportExclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_identity", models.CharField(max_length=512)),
                ("reason", models.TextField(blank=True)),
                ("report_title", models.TextField(blank=True)),
                ("report_date", models.CharField(blank=True, max_length=32)),
                ("report_url", models.URLField(blank=True, max_length=1024)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "excluded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_report_exclusions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_exclusions",
                        to="wb_workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"],
                        name="idx_wre_workspace_created",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "report_identity"),
                        name="uniq_workspace_report_exclusion",
                    )
                ],
            },
        ),
    ]
