# Generated by Django 5.2.12 on 2026-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_workspaces', '0008_user_llm_config_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userllmcredential',
            name='provider',
            field=models.CharField(choices=[('local_ollama', 'Local (Ollama)'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userllmsetting',
            name='model_name',
            field=models.CharField(default='gemma4:27b', max_length=255),
        ),
        migrations.AlterField(
            model_name='userllmsetting',
            name='provider',
            field=models.CharField(choices=[('local_ollama', 'Local (Ollama)'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], default='local_ollama', max_length=16),
        ),
        migrations.AlterField(
            model_name='workspacecredential',
            name='provider',
            field=models.CharField(choices=[('local_ollama', 'Local (Ollama)'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workspacellmsetting',
            name='model_name',
            field=models.CharField(default='gemma4:27b', max_length=255),
        ),
        migrations.AlterField(
            model_name='workspacellmsetting',
            name='provider',
            field=models.CharField(choices=[('local_ollama', 'Local (Ollama)'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], default='local_ollama', max_length=16),
        ),
    ]
